###############################################################
# Author(s): Việt Anh Bùi | https://github.com/vietanhbui2000 #
#            n0k0m3 | https://github.com/n0k0m3               #
###############################################################

name: Build ReVanced

on:
  workflow_dispatch:
  push:
    paths:
      - 'versions.json'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setup Java
      uses: actions/setup-java@v3.9.0
      with:
        distribution: "temurin"
        java-version: "17"
        java-package: jdk

    - name: Download base packages
      run: |
        chmod +x download.sh
        ./download.sh

    - name: Compile packages
      env:
        CN: ${{ secrets.KEYSTORE_CN }}
        PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      run: |
        chmod +x compile.sh
        ./compile.sh "$CN" "$PASSWORD"
        echo "date_now=$(date +'%Y%m%d')" >> $GITHUB_ENV

    - name: Upload packages
      uses: softprops/action-gh-release@v0.1.15
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag_name: "latest"
        prerelease: true
        name: "ReVanced r${{ env.date_now }}"
        files: |
          vanced-microg.apk
          output/*.keystore
          output/*.apk
