###############################################################
# Author(s): Việt Anh Bùi | https://github.com/vietanhbui2000 #
#            n0k0m3 | https://github.com/n0k0m3               #
###############################################################

name: Build ReTwitch

on:
  workflow_dispatch:
  push:
    paths:
      - 'retwitch/dl_twitch-version.json'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setup Java
      uses: actions/setup-java@v3.9.0
      with:
        distribution: "zulu"
        java-version: "17"
        java-package: jdk

    - name: Download Twitch
      run: |
        cd retwitch
        chmod +x dl_twitch.sh
        ./dl_twitch.sh

    - name: Compile ReTwitch
      run: |
        cd retwitch
        chmod +x compile_retwitch.sh
        ./compile_retwitch.sh
        echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Sign package(s)
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: retwitch/output
        alias: ${{ secrets.ALIAS }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
      env:
        BUILD_TOOLS_VERSION: "30.0.2"

    - name: Upload package(s)
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        draft: true
        title: "ReTwitch r${{ env.date_now }}"
        files: |
          retwitch/output/retwitch-signed.apk
