###############################################################
# Author(s): Việt Anh Bùi | https://github.com/vietanhbui2000 #
#            n0k0m3 | https://github.com/n0k0m3               #
###############################################################

name: Build ReReddit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setup Java
      uses: actions/setup-java@v3.3.0
      with:
        distribution: "zulu"
        java-version: "17"
        java-package: jdk

    - name: Download Reddit
      run: |
        cd rereddit
        chmod +x dl_reddit.sh
        ./dl_reddit.sh

    - name: Compile ReReddit
      run: |
        cd rereddit
        chmod +x compile_rereddit.sh
        ./compile_rereddit.sh
        echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Sign packages
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: rereddit/output
        alias: ${{ secrets.ALIAS }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
      env:
        BUILD_TOOLS_VERSION: "30.0.2"

    - name: Upload packages
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        draft: true
        title: "r${{ env.date_now }}"
        files: |
          rereddit/output/rereddit-signed.apk
